### PR TITLE
Update Josm_FranceSpecificRules mapcss (added name~covoiturage rule)

### PR DESCRIPTION
**Pull request by PanierAvide**
Hello,
I added some rules in the MapCSS for France regarding carpooling areas. If a feature contains a name similar to "covoiturage", we add carpooling tags. I hope I got the Mapcss rules update right this time ^^
Regards,
Adrien.

### CODE REVIEW

**Comment by frodrigo** [comment]
The file `item_map.py` should also be commit. Generate, edit the file, Generate, then commit.

**Comment by PanierAvide** [comment]
When I update the MapCSS plugin, item_map.py is not changed. What should I edit exactly ? Maybe we can work on documentation to make this more explicit.

**Comment by frodrigo** [comment]
You are right, since the mapcss file content osmose element it's ok.

Place can you switch the item and class to 2080/20806, avoid to create a new item just for that.

**Comment by PanierAvide** [comment]
Great, so I changed the class as required :-)

**Comment by frodrigo** [comment]
Thank.

**Pull request merged**
